# Laboratorium 4 — NumPy zaawansowane
**Autor:** Jakub Kulig


In [2]:
import numpy as np


Ćwiczenie 1: Broadcasting — zastosowania biznesowe (20
min)

Krok 1 — Dane

In [3]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


Krok 2 — Zadania
Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja).
Wyświetl wynik.

In [4]:

# Broadcasting: macierz (4×3) * skalar
# Podpowiedź: ceny * 1.05

print(ceny*1.05)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat:
Centrum 10%, Galeria 5%, Online 15%.


In [5]:
# Broadcasting: macierz (4×3) * wektor (3,)
# Podpowiedź: ceny * (1 - rabaty)
# Wektor 3-elementowy pasuje do 3 kolumn — broadcasting wierszowy
rabaty = np.array([0.10, 0.05, 0.15])
print(ceny * (1 - rabaty) )

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną
marżę: A=30%, B=40%, C=25%, D=50%

In [9]:

# Broadcasting: macierz (4×3) * wektor kolumnowy (4×1)
# Oblicz koszt zakupu: cena / (1 + marża)
# Podpowiedź: marża jest kolumną (4×1) — broadcasting kolumnowy
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
print(ceny / (1+marza))

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.

In [12]:
# Podpowiedź: użyj .argmin(axis=1) i listy sklepów
s_ar= np.array(sklepy)
print(f'najtańszy sklap dla każdego produktu to {s_ar[ceny.argmin(axis=1)]}')

najtańszy sklap dla każdego produktu to ['Online' 'Online' 'Online' 'Online']


Ćwiczenie 2: Reshape i łączenie danych (20 min)
Cel
Zmień kształt danych i połącz tablice z różnych źródeł.

Zadanie 2a — Reshape

In [14]:

# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b — Stacking

In [15]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c — Praktyczne (samodzielnie)

In [27]:
# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące
# 1. Reshape na macierz 6×2
# Podpowiedź: sprzedaz_flat.reshape(6, 2) albo .reshape(-1, 2)
sprzedaz = sprzedaz_flat.reshape(6, 2)
print(f'sprzedarz \n {sprzedaz}')
# 2. Oblicz średnią sprzedaż per produkt (axis=1)
srednia = sprzedaz.mean(axis=1)
print(f'Średnia to\n {srednia}')
# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
# Podpowiedź: macierz[:, 1] - macierz[:, 0]
roznica = np.array(sprzedaz[:,1] - sprzedaz[:,0])
print(f'Różnica dla każdego produktu\n{roznica}')


sprzedarz 
 [[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Średnia to
 [150. 225. 215. 170. 240. 225.]
Różnica dla każdego produktu
[100 150 -70 100 140 -70]


Zadanie 2d — Flatten i concatenate

In [32]:
# Masz macierz kwartałów z zadania 2a
# 1. Spłaszcz ją z powrotem do wektora (.flatten())
kwartaly_flat=kwartaly.flatten()
print(kwartaly_flat)
# 2. Dodaj dane z 13. miesiąca (wartość: 235) — np.concatenate()
xiii = np.concatenate([kwartaly_flat, np.array([235])])
# Podpowiedź: np.concatenate([wektor, np.array([235])])
print(xiii)

[120 135  98 142 167 189 201 178 156 143 198 221]
[120 135  98 142 167 189 201 178 156 143 198 221 235]


Ćwiczenie 3: Analiza danych finansowych (30 min)
Cel
Samodzielna analiza danych finansowych firmy z użyciem zaawansowanych operacji NumPy.


In [4]:
np.random.seed(6767)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])


Zadanie 3a: Analiza wynagrodzeń

In [ ]:
# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
# Podpowiedź: pensje.mean(), np.median(pensje), pensje.std()
srednia = pensje.mean()
med = np.median(pensje)
odch = pensje.std()
print(f'Średnia wynosi: {srednia} \nMediana wynosi: {med} \nOdchylenie wynosi {odch}')
# 2. Wyświetl imiona osób zarabiających powyżej średniej
# Uwaga: pracownicy to lista — zamień na np.array(pracownicy), żeby użyć maski
# Podpowiedź: nazwy = np.array(pracownicy), potem nazwy[pensje > pensje.mean()]
name = np.array(pracownicy)
temp1= name[pensje> srednia]
print(temp1)
# 3. Wyświetl imiona osób zarabiających poniżej mediany
temp2 = name[pensje< med]
print(temp2)
# 4. Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)
# Podpowiedź: IQR = np.percentile(pensje, 75) - np.percentile(pensje, 25)

roz= pensje.max() - pensje.min()
IQR= np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f"Rozstęp(max-min) {roz}")
print(f'Rozstęp IQR wynosi:{IQR}')

Średnia wynosi: 6425.0 
Mediana wynosi: 6050.0 
Odchylenie wynosi 1616.9029037020127
['Jan' 'Marek' 'Zofia']
['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp(max-min) 4900
Rozstęp IQR wynosi:2200.0 


Zadanie 3b: System premii (np.where)

In [17]:
# Zasady premii:
# - ocena >= 4.5 → premia 2000 zł
# - ocena >= 4.0 → premia 1000 zł
# - ocena < 4.0 → premia 0 zł
# Podpowiedź: zagnieżdżony where:
# np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
# Oblicz nowe wynagrodzenie (pensja + premia)
# Kto dostał najwyższą premię? Użyj argmax()
name = np.array(pracownicy)
premie = np.where(oceny >= 4.5, 2000,
         np.where(oceny >= 4.0, 1000, 0))
nowe_wynagrodzenie = pensje + premie
print(f'Nowe wynagrodzenie to {nowe_wynagrodzenie}')

idx = premie.argmax()
najlepszy_pracownik = pracownicy[idx]
print(f'Najlepszy pracownik to: {najlepszy_pracownik}')



Nowe wynagrodzenie to [ 6500  7200  6800 10100  8300  4200  9500  5800]
Najlepszy pracownik to: Ewa


Zadanie 3c: Ranking (argsort)


In [23]:
# Posortuj pracowników wg pensji (od najwyższej)
# Podpowiedź: kolejnosc = np.argsort(pensje)[::-1]
# Wyświetl ranking: pozycja, imię, pensja, staż
# Podpowiedź: for i, idx in enumerate(kolejnosc, 1): ...
kolejnosc = np.argsort(pensje)[::-1]
temp_i= np.array(pracownicy)

print(f'pracownicy posotrowni według pensji: {temp_i[kolejnosc]}')

for i, idx in enumerate(kolejnosc, 1):
    print(f'{i}. {pracownicy[idx]} | pensja: {pensje[idx]} zł | staż: {staz[idx]} lat')

pracownicy posotrowni według pensji: ['Marek' 'Zofia' 'Jan' 'Kasia' 'Tomek' 'Anna' 'Ewa' 'Piotr']
1. Marek | pensja: 9100 zł | staż: 15 lat
2. Zofia | pensja: 8500 zł | staż: 12 lat
3. Jan | pensja: 7200 zł | staż: 8 lat
4. Kasia | pensja: 6300 zł | staż: 5 lat
5. Tomek | pensja: 5800 zł | staż: 4 lat
6. Anna | pensja: 5500 zł | staż: 3 lat
7. Ewa | pensja: 4800 zł | staż: 2 lat
8. Piotr | pensja: 4200 zł | staż: 1 lat


Zadanie 3d: Korelacja

In [26]:
# Oblicz korelację: staż vs pensja
# Podpowiedź: np.corrcoef(staz, pensje)[0, 1]

corr_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
print(f'Korelacja stażvs pensja wynosi: {corr_staz_pensja}')

# Oblicz korelację: staż vs ocena
# Który związek jest silniejszy? (wyższa wartość bezwzględna r)
corr_staz_ocena = np.corrcoef(staz, oceny)[0, 1]
print(f'Kolerlacja staż vs ocena wynosi: {corr_staz_ocena}')

Korelacja stażvs pensja wynosi: 0.987862864584301
Kolerlacja staż vs ocena wynosi: 0.04198471605953068


Zadanie 3e: Analiza sprzedaży (broadcasting)

In [29]:
# Oblicz przychód: sprzedaz (4×6) * ceny_produktow (4,) — UWAGA na broadcasting!
# Problem: (4,6) * (4,) — nie pasuje! 6 != 4
# Rozwiązanie: ceny muszą być kolumną (4×1)
# Podpowiedź: ceny_kol = ceny_produktow.reshape(4, 1)
# przychod = sprzedaz * ceny_kol
# Który produkt przyniósł największy łączny przychód? (axis=1, argmax)
# Który miesiąc był najlepszy łącznie? (axis=0, argmax)
# Trend: porównaj pierwsze 3 miesiące vs ostatnie 3
# Podpowiedź: przychod[:, :3].sum() vs przychod[:, 3:].sum()

ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol
przychod_produkty = przychod.sum(axis=1)
najlepszy_produkt = przychod_produkty.argmax()

print(f'Najlepiej zarabiający produkt to: {produkty_nazwy[najlepszy_produkt]}')

przychod_miesiace = przychod.sum(axis=0)
najlepszy_miesiac = przychod_miesiace.argmax()

print(f'Najlepiej zarabiający miesiąc: {najlepszy_miesiac + 1}')

pierwsze_3 = przychod[:, :3].sum()
ostatnie_3 = przychod[:, 3:].sum()

print(f'W pierwszych 3 miesiącach przychód wyniósł {pierwsze_3}, a w ostatnich 3 miesiącach {ostatnie_3}. Oznacza to wzrost sprzedaży w drugiej połowie okresu.')

Najlepiej zarabiający produkt to: Smartfon
Najlepiej zarabiający miesiąc: 4
W pierwszych 3 miesiącach przychód wyniósł 2209700, a w ostatnich 3 miesiącach 3087500. Oznacza to wzrost sprzedaży w drugiej połowie okresu.


Ćwiczenie 4: Generowanie danych (15 min)
Cel
Wygeneruj realistyczne dane biznesowe i przeanalizuj je

In [5]:
np.random.seed(42)
# Wygeneruj dane o 100 klientach sklepu:
# - wiek: rozkład normalny, średnia 35, std 10, zaokrąglony do int, min 18
# - wydatki_miesiecznie: rozkład normalny, średnia 500, std 200, min 0
# - liczba_wizyt: rozkład Poissona, lambda=5
# Podpowiedź: np.clip() ogranicza wartości do zakresu
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

Krok 2 — Analiza (samodzielnie)


In [8]:
# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
# Podpowiedź: print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std: {wiek.std():.1f}, min: {wiek.min()}, max: {wiek.max()}")

print(f"Wydatki — średnia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, std: {wydatki.std():.1f}, min: {wydatki.min():.1f}, max: {wydatki.max():.1f}")

print(f"Wizyty — średnia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, std: {wizyty.std():.1f}, min: {wizyty.min()}, max: {wizyty.max()}")

# 2. Korelacja wiek vs wydatki
# Podpowiedź: np.corrcoef(wiek, wydatki)[0, 1]
corr_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
print(f"Korelacja wiek vs wydatki: {corr_wiek_wydatki:.2f}")

# 3. Korelacja wizyty vs wydatki
corr_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]
print(f"Korelacja wizyty vs wydatki: {corr_wizyty_wydatki:.2f}")

# 4. Segmentacja klientów za pomocą np.where:
# - "WYSOKI" gdy wydatki > średnia + std
# - "NISKI" gdy wydatki < średnia - std
# - "ŚREDNI" w pozostałych przypadkach
# Podpowiedź: zagnieżdżony np.where (jak w zadaniu 3b)
# sr = wydatki.mean()
# sd = wydatki.std()
# segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚR# 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)
sr = wydatki.mean()
sd = wydatki.std()
segment = np.where(wydatki > sr + sd, 'WYSOKI',
          np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

print(f"WYSOKI: {(segment == 'WYSOKI').sum()}")
print(f"ŚREDNI: {(segment == 'ŚREDNI').sum()}")
print(f"NISKI: {(segment == 'NISKI').sum()}")

Wiek — średnia: 33.6, mediana: 33.0, std: 8.6, min: 18, max: 53
Wydatki — średnia: 504.5, mediana: 516.8, std: 189.8, min: 116.2, max: 1044.0
Wizyty — średnia: 4.9, mediana: 5.0, std: 2.2, min: 1, max: 11
Korelacja wiek vs wydatki: -0.12
Korelacja wizyty vs wydatki: -0.16
WYSOKI: 12
ŚREDNI: 71
NISKI: 17
